services:
    api:
        container_name: api
        build:
            context: ./
            dockerfile: Dockerfile_Backend
        environment:
            TZ: 'Europe/Zurich'
            LOGS_FOLDER: '/logs'
            USER_CONFIG_FILE_PATH: '/config.json'
        volumes:
            - logs:/logs
        networks:
            borneo:
                aliases:
                    - api
        configs:
            -   source: user_config
                target: /config.json
        # List of secrets containing API keys
        secrets:
            - jwtSecret
            - spApiKey
            - elpApiKey
            - elpPassword
            - spPassword
        restart: always

    frontend:
        container_name: frontend
        build:
            context: ./
            dockerfile: Dockerfile_Frontend
        networks:
            borneo:
                aliases:
                    - frontend
        restart: always
        depends_on:
            - api

    proxy:
        container_name: proxy
        image: nginx:1-alpine
        networks:
            borneo:
                aliases:
                    - proxy
        configs:
            -   source: proxi_config
                target: /etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
            - "443:443"
        restart: always
        depends_on:
            - api
            - frontend

volumes:
    logs:

networks:
    borneo:

configs:
    user_config:
        file: ./backend/src/config.prod.json
    proxi_config:
        file: ./proxy/default.conf

# Secrets containing API keys
secrets:
    jwtSecret:
        file: ./backend/src/secrets/jwt.secret
    spApiKey:
        file: ./backend/src/secrets/sp.apiKey
    elpApiKey:
        file: ./backend/src/secrets/elp.apiKey
    elpPassword:
        file: ./backend/src/secrets/elp.password
    spPassword:
        file: ./backend/src/secrets/sp.password
